version: "3.5"
services:
 vite_docker:
   image: node:alpine
   container_name: asn-page
   entrypoint: /bin/sh
   ports:
     - 4999:4999
   working_dir: /srv/asnpage
   volumes:
     - type: bind
       source: ./
       target: /srv/asnpage
   tty: true